# Specify reviewers for pull requests

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "yenchenLiu"
