version: "3"
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - db_charity_helper:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile
    command: uvicorn app.main:app --reload
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres@db/charity
    volumes:
      - ./:/usr/src/app


volumes:
  db_charity_helper:
    driver: local
